### ISSUE TITLE
Marker Touch Events not Working

### ISSUE THREAD

**Issue by birdm4n** [chrisrzhou/react-globe#45] opened 2020-10-05 12:17 UTC
Touch events are not fired when clicking on markers. Gestures (swipe/zoom etc.) work well but touch inputs are not handled when one taps on a marker. Tested on different machines with touch emulation and with real touch screen.

**Comment by chrisrzhou** [comment] 2020-10-15 18:37
duplicate of #44, closing.

**Closed as completed by chrisrzhou** 2020-10-15 18:37 UTC
Labels: duplicate
